name: CI

on:
  push:
    branches:
      - master
      - 'feature-**'
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Audit
        run: npm audit --audit-level=high
